markdown: redcarpet
name: Agile Scrum Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Government of British Columbia
  url: https://www.gov.bc.ca

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: About This Guide
  internal: true
- text: What is Agile?
  url: ag_intro/
  internal: true
- text: Getting Started
  url: ag_getstarted/
  internal: true
- text: Align With Agile and Scrum
  url: ag_alignwithagile/
  internal: true
- text: Create Your Scrum Environment
  url: ag_create_env/
  internal: true
- text: Create Your Scrum Team
  url: ag_create_team/
  internal: true
- text: Agile Maturity Matrix
  url: ag_Agile_Scrum_Maturity_Matrix/
  internal: true
- text: Test To See If Your Agile
  url: ag_Agility_Profile.md/
  internal: true

repos:
- name: BC Agile Scrum Guide
  description: Main repository
  url: https://github.com/bcgov/agile-guide

back_link:
  url: "https://guides.pathfinder.bcgov"
  text: Read more BC Government Guides

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
